#!/usr/bin/env python3
import os
import sqlite3
import json
import time
import argparse
import smtplib
from email.mime.text import MIMEText

try:
    from dotenv import load_dotenv
    import google.genai as genai
except ImportError:
    import subprocess
    import sys
    import os
    print("-> Missing required packages. Installing python-dotenv and google-genai...", flush=True)
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "python-dotenv", "google-genai"])
    except subprocess.CalledProcessError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "python-dotenv", "google-genai", "--break-system-packages"])
    
    print("-> Packages installed! Restarting script to load them...", flush=True)
    os.execv(sys.executable, [sys.executable] + sys.argv)

# Load environment variables from .env
load_dotenv()

DB_FILE = os.path.join("data", "pulse_history.db")
G_KEY = os.environ.get("GEMINI_API_KEY", "")

if not G_KEY:
    print("Error: GEMINI_API_KEY not found in your environment/ .env file.")
    exit(1)

client = genai.Client(api_key=G_KEY)

def send_report_email(subject, body):
    msg = MIMEText(body)
    msg['Subject'] = subject
    msg['From'] = os.environ.get("SMTP_USER", "buddy-alerts@morrowedge.com")
    msg['To'] = "joseph@morrowedge.com"
    
    smtp_server = os.environ.get("SMTP_SERVER", "localhost")
    smtp_port = int(os.environ.get("SMTP_PORT", 587))
    try:
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            if os.environ.get("SMTP_USER") and os.environ.get("SMTP_PASS"):
                server.starttls()
                server.login(os.environ.get("SMTP_USER"), os.environ.get("SMTP_PASS"))
            server.send_message(msg)
        print("-> Email report sent successfully.")
    except Exception as e:
        print(f"-> [ERROR] Failed to send email: {e}")

def setup_db():
    os.makedirs(os.path.dirname(DB_FILE), exist_ok=True)
    with sqlite3.connect(DB_FILE) as conn:
        conn.execute('''CREATE TABLE IF NOT EXISTS pulses (
                            id INTEGER PRIMARY KEY AUTOINCREMENT,
                            date TEXT,
                            text TEXT UNIQUE
                         )''')
        conn.execute('''CREATE TABLE IF NOT EXISTS hallucinations_log (
                            id INTEGER PRIMARY KEY AUTOINCREMENT,
                            retrieved_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                            date TEXT,
                            text TEXT,
                            reason TEXT
                         )''')

def check_hallucination(text):
    prompt = f"""
You are a fact-checking assistant evaluating historical "Pulse" events for Sault Ste. Marie, Michigan.
Many of these entries were generated by an AI that was overly constrained and forced to hallucinate fake events (like fake farmers markets, fake community gatherings with specific times like '9:00 AM to 1:00 PM', or overly dramatic fictional milestones).

Examine the following text. Determine if it is likely a hallucinated/invented event, or if it is a generic factual seasonal observation (like freighters, weather, bridge glow). 

Text: "{text}"

Return ONLY a valid JSON object in this exact format:
{{
  "hallucinated": true/false,
  "reason": "Brief explanation of why you made this determination."
}}
"""
    try:
        response = client.models.generate_content(
            model="models/gemini-1.5-flash",
            contents=prompt,
        )
        resp_text = response.text
        json_str = resp_text[resp_text.find('{'):resp_text.rfind('}')+1]
        data = json.loads(json_str)
        return data.get("hallucinated", False), data.get("reason", "No reason provided")
    except Exception as e:
        print(f"Error checking text: {e}")
        return False, str(e)

RED = '\033[91m'
RESET = '\033[0m'

def main():
    parser = argparse.ArgumentParser(description="Hallucination Cleanup Script")
    parser.add_argument("--run-auto", action="store_true", help="Run automated cleanup round and email results.")
    parser.add_argument("--list-previous-hallucinations", action="store_true", help="List dates/names and retrieval times.")
    parser.add_argument("--print-previous-hallucinations", action="store_true", help="Print full details of all stored hallucinations.")
    args = parser.parse_args()

    setup_db()

    if args.list_previous_hallucinations:
        with sqlite3.connect(DB_FILE) as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT id, date, retrieved_at FROM hallucinations_log ORDER BY retrieved_at DESC")
            rows = cursor.fetchall()
            print("--- Previous Hallucinations (List) ---")
            if not rows: print("No recorded hallucinations.")
            for r in rows:
                print(f"ID: {r[0]} | Date: {r[1]} | Retrieved At: {r[2]}")
        return

    if args.print_previous_hallucinations:
        with sqlite3.connect(DB_FILE) as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT id, date, retrieved_at, text, reason FROM hallucinations_log ORDER BY retrieved_at DESC")
            rows = cursor.fetchall()
            print("--- Previous Hallucinations (Full Details) ---")
            if not rows: print("No recorded hallucinations.")
            for r in rows:
                print(f"[{r[0]}] Date: {r[1]} | Retrieved: {r[2]}\nText: {r[3]}\nReason: {r[4]}\n")
        return

    with sqlite3.connect(DB_FILE) as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT id, date, text FROM pulses")
        pulses = cursor.fetchall()

        print(f"Found {len(pulses)} pulses in history. Starting analysis...\n")
        
        round_results = []

        for pulse_id, date, text in pulses:
            print(f"Analyzing [{pulse_id}] {date}: {text}", flush=True)
            is_hallucinated, reason = check_hallucination(text)
            
            if is_hallucinated:
                print(f"{RED}-> [HALLUCINATION DETECTED] {reason}{RESET}", flush=True)
                cursor.execute("INSERT INTO hallucinations_log (date, text, reason) VALUES (?, ?, ?)", (date, text, reason))
                cursor.execute("DELETE FROM pulses WHERE id = ?", (pulse_id,))
                conn.commit()
                print(f"{RED}-> Deleted Pulse ID: {pulse_id}\n{RESET}", flush=True)
                round_results.append((date, text, reason))
            else:
                print(f"-> [VALID] {reason}\n", flush=True)
                
            time.sleep(1) # Prevent hitting API rate limits
            
        # Keep only the last 100 entries in the log
        cursor.execute('''DELETE FROM hallucinations_log 
                          WHERE id NOT IN (
                              SELECT id FROM hallucinations_log 
                              ORDER BY retrieved_at DESC 
                              LIMIT 100
                          )''')
        conn.commit()

        print("Cleanup complete!", flush=True)
        
        if args.run_auto:
            if not round_results:
                subject = "[BEACON BUDDY] - Hallucination Cleanup: None Found"
                body = "The scheduled hallucination cleanup ran successfully.\n\nNo hallucinations were detected in this round."
            else:
                subject = f"[BEACON BUDDY] - Hallucination Cleanup: {len(round_results)} Removed"
                body = f"The scheduled hallucination cleanup detected and removed {len(round_results)} hallucinated entries:\n\n"
                for res in round_results:
                    body += f"Date: {res[0]}\nText: {res[1]}\nReason: {res[2]}\n\n"
            
            send_report_email(subject, body)
        else:
            if round_results:
                print(f"\n{RED}--- Summary: {len(round_results)} Hallucinations Removed ---{RESET}")
                for res in round_results:
                    print(f"{RED}Date: {res[0]}\nText: {res[1]}\nReason: {res[2]}\n{RESET}")
            else:
                print("\n--- Summary ---")
                print("No hallucinations were detected during this run.")

if __name__ == "__main__":
    main()